### ISSUE TITLE
能否移植到linux

### ISSUE THREAD

**Issue by q1e2e3q** [Ryan-CW-Code/RyanMqtt#1]
仔细看了readme，如果没有使能 ulog 或者非 RT-Thread 平台，用户需要手动修改 RyanMqttLog.h 文件调整打印等级，其中RyanMqttLog.h 在源码中没有找到啊？

**Comment by Ryan-CW-Code** [comment]
可以，log组件重构了。
但是linux平台有更好的选择，如果只需要支持mqtt3.1.1的话RyanMqtt会是个好选择。
否则linux平台可以看看 [wolfMQTT](https://github.com/wolfSSL/wolfMQTT)
