### ISSUE TITLE
keepalive自动重连问题

### ISSUE THREAD

**Issue by ddleed** [Ryan-CW-Code/RyanMqtt#4]
最新的代码   rtthread平台
如果下位机不周期发布消息，自动重连功能就失效了，周期100ms发布消息就没问题
![image](https://github.com/user-attachments/assets/9c7b727e-8806-4e62-9f17-80cb99a03d2b)

**Comment by Ryan-CW-Code** [comment]
`keepalive`不要设置这么短，为了节约资源`keepalive`是在`recvTimeout`后进行检查的。
代表`recvTimeout`循环一次进行检查，检查心跳时间超过设置的0.8倍事件后发送心跳的。

**Comment by Ryan-CW-Code** [comment]
这部分我看看咋优化下吧

**Comment by ddleed** [comment]
用了优化的代码，没有效果。

keepalive设置30s，关掉mqtt服务器的网卡，模拟服务器掉线。

- 拔插板卡的网线，mqtt会立即重连

- 如果下位机循环发数据，大概44s会触发自动重连，打开mqtt服务器的网卡会自动连接

- 如果下位机不发数据，等待60s后，没有触发自动重连，打开mqtt服务器的网卡也不行

**Comment by Ryan-CW-Code** [comment]
> 用了优化的代码，没有效果。
> 
> keepalive设置30s，关掉mqtt服务器的网卡，模拟服务器掉线。
> 
> * 拔插板卡的网线，mqtt会立即重连
> * 如果下位机循环发数据，大概44s会触发自动重连，打开mqtt服务器的网卡会自动连接
> * 如果下位机不发数据，等待60s后，没有触发自动重连，打开mqtt服务器的网卡也不行

条件2、3是在条件1的前提下吗？   
如果使能了自动重连可以尝试排除掉`mqtt线程有没有得到执行`、`recv真实超时时间不是设置的5000ms`
我用at_socket模拟你说的网卡断网，重连是可以的，你可以先排除下上面两个问题。

**Comment by ddleed** [comment]
三个条件是独立测试的

**Comment by Ryan-CW-Code** [comment]
![image](https://github.com/user-attachments/assets/8415e034-8aba-4fad-b4f5-819d86d1c063)

**Comment by Ryan-CW-Code** [comment]
刷新keepalive会在收到`心跳响应`、`mqtt报文发送成功`
这个是网络层无法检测到网络断开了。
你用的是lwip吗？就算你是直接关的mqtt服务器网卡，lwip也不应该这么久都没监测到tcp链路断了。

### 通义的回答

LWIP 默认的 TCP 超时时间涉及到多个方面，主要包括重传超时（RTO）和其他一些超时参数。这些参数可以根据具体的应用需求进行调整，但默认情况下，LWIP 设定了一些基本的值。下面是一些关键参数及其默认值：

### 重传超时（RTO）

RTO 是 TCP 重传数据包之前的等待时间。在 LWIP 中，RTO 的计算基于对往返时间（RTT）的估计，并且它是一个动态调整的时间间隔。尽管 RTO 的确切值是动态的，但 LWIP 提供了一些默认值作为初始估算。

- **初始 RTO 时间**：LWIP 的初始 RTO 通常是 1 秒。这是指在第一次重传之前等待的时间。如果数据包丢失并且没有收到 ACK 确认，LWIP 会在 1 秒后重传数据包。
- **动态调整**：之后的 RTO 会根据 RTT 的估计值进行调整。如果网络条件良好，RTO 可能会缩短；如果网络状况不佳，RTO 可能会延长。

### TCP 保活机制（Keepalive）

LWIP 支持 TCP 保活机制，用于在长时间无数据传输时保持连接的活跃状态。保活机制通过定期发送探测包来检查连接是否仍然有效。

- **TCP 保活时间（TCP_KEEPIDLE）**：默认情况下，LWIP 的 TCP 保活时间是 2 小时（7200 秒）。这意味着在没有数据传输的情况下，LWIP 会等待 2 小时后开始发送保活探测包。
- **TCP 保活间隔（TCP_KEEPINTVL）**：默认的保活间隔是 75 秒。这意味着在开始发送保活探测包后，每隔 75 秒会发送一次探测包。
- **TCP 保活尝试次数（TCP_KEEPCNT）**：默认的保活尝试次数是 9 次。这意味着如果在发送了 9 次探测包后仍未收到任何回应，LWIP 认为连接已经断开。

### 最大段生存期（MSL）

MSL（Maximum Segment Lifetime）是指 TCP 数据段在网络中存活的最大时间。在 TCP 连接终止后，发送端会进入 TIME_WAIT 状态，并等待 2 倍 MSL 的时间，以确保所有数据段都已经在网络中消失。

- **MSL 时间**：LWIP 默认的 MSL 时间是 2 分钟（120 秒）。

### 总结

根据上述参数，我们可以总结出 LWIP 默认情况下检测到 TCP 连接断开的时间如下：

- **没有启用 TCP 保活机制**：如果没有任何数据传输，并且对端也没有发送任何 ACK 确认，那么 LWIP 会等待 RTO 超时时间后重传数据包。如果连续几次重传失败，LWIP 会认为连接已经断开。在最坏的情况下，这可能需要几分钟的时间。
- **启用 TCP 保活机制**：如果启用了 TCP 保活机制，那么在 2 小时后开始发送探测包，并且每隔 75 秒发送一次，总共发送 9 次。如果 9 次探测都未得到回应，LWIP 会认为连接已经断开。这意味着在最坏的情况下，LWIP 需要大约 2 小时 11 分 15 秒才能检测到断开。

这些参数都是可以调整的，您可以通过修改 LWIP 的配置文件来改变这些默认值，以适应特定的应用场景。例如，您可以缩短保活时间和间隔来更快地检测到连接断开。

**Comment by ddleed** [comment]
请看一下qq消息吧，我网络比较卡，图片很难上传

用的lwip2.1.2，拔插网卡可以立即检测到

![image](https://github.com/user-attachments/assets/e89afe1d-6e3e-4f58-90ff-8a187c32e9f8)
